# Generated by Django 5.2 on 2025-06-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
