# Generated by Django 5.2 on 2025-06-27 00:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemreserva', '0001_initial'),
        ('reservas', '0001_initial'),
        ('veiculos', '0002_alter_veiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemreserva',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Item de Reserva', 'verbose_name_plural': 'Itens de Reserva'},
        ),
        migrations.AddField(
            model_name='itemreserva',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre esta reserva', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='data_fim',
            field=models.DateField(help_text='Data prevista de devolução', verbose_name='Data de término'),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='data_inicio',
            field=models.DateField(help_text='Data de retirada do veículo', verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_reserva', to='reservas.reserva', verbose_name='Reserva associada'),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, help_text='Valor por dia do veículo', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da diária'),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='valor_parcial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculado automaticamente (diárias + acessórios)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor parcial'),
        ),
        migrations.AlterField(
            model_name='itemreserva',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_reserva', to='veiculos.veiculo', verbose_name='Veículo reservado'),
        ),
        migrations.AddIndex(
            model_name='itemreserva',
            index=models.Index(fields=['data_inicio', 'data_fim'], name='itemreserva_data_in_50d844_idx'),
        ),
        migrations.AddIndex(
            model_name='itemreserva',
            index=models.Index(fields=['valor_parcial'], name='itemreserva_valor_p_c894f1_idx'),
        ),
    ]
