# Generated by Django 5.2 on 2025-06-26 23:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor total do pagamento')),
                ('metodo', models.CharField(choices=[('CARTAO', 'Cartão de Crédito/Débito'), ('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário')], max_length=10, verbose_name='Método de pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='PENDENTE', max_length=10, verbose_name='Status do pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('dados_transacao', models.JSONField(blank=True, null=True, verbose_name='Dados da transação (gateway de pagamento)')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='reservas.reserva', verbose_name='Reserva associada')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
