# Generated by Django 5.2 on 2025-06-27 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acessorios', '0001_initial'),
        ('itemreserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoAcessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_adicional', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Adicional (por dia)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_acessorios', to='acessorios.acessorio', verbose_name='Acessório')),
                ('item_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_acessorios', to='itemreserva.itemreserva', verbose_name='Item de Reserva')),
            ],
            options={
                'verbose_name': 'Acessório de Veículo (Reserva)',
                'verbose_name_plural': 'Acessórios de Veículo (Reserva)',
                'unique_together': {('item_reserva', 'acessorio')},
            },
        ),
    ]
