# Generated by Django 5.2 on 2025-06-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_valor_base'),
    ]

    operations = [
    ]
